### ISSUE TITLE
Add contributing infrastructure

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/hyp3-paper#3]
It'd be nice to have a few things setup to make contributing easier:

- [x] contributing guide
- [x] draft PDF workflow
- [x] spell check workflow
- [x] CODEOWNERS for reviewers
- [x] [won't do] bibtex linting workflow
- [x] link checker workflow

**Comment by forrestfwilliams** [comment]
For workflows, I've identified a [spellchecker](https://github.com/marketplace/actions/spellchecker-cli-summary), a [markdown linter](https://github.com/marketplace/actions/markdown-linting-action), a [link checker](https://github.com/marketplace/actions/lychee-broken-link-checker), and the JOSS [pdf builder](https://github.com/ICESat2-SlideRule/paper/blob/main/.github/workflows/draft-pdf.yml). I wasn't able to identify a bibtex-specific linter, but there are some latex linters. I'm not sure if these would be appropriate.

**Comment by jacquelynsmale** [comment]
As for bibtex checkers, there's [BibtexNanny](https://github.com/marcschulder/BibTexNanny) and [BibLatex-Check](https://github.com/Pezmc/BibLatex-Check). BibLatex-Check isn't under active development but is still functional.

**Comment by jacquelynsmale** [comment]
@jhkennedy there aren't any pre-built workflows to lint the BibTex file. Is this worth writing our own for or do you think the error message produced if there's something wrong with the bib file during the PDF build will be sufficient?

**Comment by jhkennedy** [comment]
@jacquelynsmale the PDF build is likely sufficient. Let's mark that task as done indicating it's a `won't do` and re-open it if we find the PDF build route is not working for us.

**Comment by forrestfwilliams** [comment]
Contributing guidelines PR is now open.

**Comment by forrestfwilliams** [comment]
Long term, it would be great if [Grammarly supported a GtiHub Action](https://github.com/grammarly/grammarly-for-developers/discussions/306). I've really enjoyed using it for manuscripts in the past.

**Comment by forrestfwilliams** [comment]
All components are now complete.
